name: Get the latest Kernel release for Stable
on:
  push:
    branches:
      - "flatcar-master"

jobs:
  get-kernel-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch latest Kernel release
        id: fetch-latest-release
        env:
          KV_STABLE: 4.19
        run: |
          git clone --depth=1 --no-checkout https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git linux
          versionStable=$(git -C linux ls-remote --tags origin | cut -f2 | sed -n "/refs\/tags\/v${KV_STABLE}.[0-9]*$/s/^refs\/tags\/v//p" | sort -ruV | head -1)
          rm -rf linux
          echo ::set-output name=VERSION_STABLE::$(echo ${versionStable})
          echo ::set-output name=BASE_BRANCH_STABLE::flatcar-master
      - name: Set up Flatcar SDK
        id: setup-flatcar-sdk
        run: .github/workflows/setup-flatcar-sdk.sh
      - name: Apply patch for Stable
        id: apply-patch-stable
        env:
          CHANNEL: stable
          BASE_BRANCH: ${{ steps.fetch-latest-release.outputs.BASE_BRANCH_STABLE }}
          PATH: ${{ steps.setup-flatcar-sdk.outputs.path }}
          VERSION_NEW: ${{ steps.fetch-latest-release.outputs.VERSION_STABLE }}
        run: .github/workflows/kernel-apply-patch.sh
      - name: Create pull request for Stable
        uses: peter-evans/create-pull-request@v2
        if: steps.apply-patch-stable.outputs.UPDATE_NEEDED == 1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ steps.fetch-latest-release.outputs.BASE_BRANCH_STABLE }}
          branch: linux-${{ steps.fetch-latest-release.outputs.VERSION_STABLE }}-stable
          author: Flatcar Buildbot <buildbot@flatcar-linux.org>
          committer: Flatcar Buildbot <buildbot@flatcar-linux.org>
          title: Upgrade Linux Kernel in Stable from ${{ steps.apply-patch-stable.outputs.VERSION_OLD }} to ${{ steps.fetch-latest-release.outputs.VERSION_STABLE }}
          commit-message: Upgrade Linux Kernel in Stable from ${{ steps.apply-patch-stable.outputs.VERSION_OLD }} to ${{ steps.fetch-latest-release.outputs.VERSION_STABLE }}
          body: Upgrade Linux Kernel in Stable from ${{ steps.apply-patch-stable.outputs.VERSION_OLD }} to ${{ steps.fetch-latest-release.outputs.VERSION_STABLE }}
          labels: stable
