name: Get the latest Rust release for Alpha
on:
  push:
    branches:
      - "flatcar-master"

jobs:
  get-rust-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch latest Rust release
        id: fetch-latest-release
        run: |
          git clone --depth=1 --no-checkout https://github.com/rust-lang/rust
          versionAlpha=$(git -C rust ls-remote --tags origin | cut -f2 | sed -n "/refs\/tags\/1.[0-9]*.[0-9]*$/s/^refs\/tags\///p" | sort -ruV | head -n1)
          rm -rf rust
          echo ::set-output name=VERSION_ALPHA::$(echo ${versionAlpha})
          echo ::set-output name=BASE_BRANCH_ALPHA::flatcar-master-alpha
      - name: Set up Flatcar SDK
        id: setup-flatcar-sdk
        run: .github/workflows/setup-flatcar-sdk.sh
      - name: Apply patch for Alpha
        id: apply-patch-alpha
        env:
          CHANNEL: alpha
          BASE_BRANCH: ${{ steps.fetch-latest-release.outputs.BASE_BRANCH_ALPHA }}
          PATH: ${{ steps.setup-flatcar-sdk.outputs.path }}
          VERSION_NEW: ${{ steps.fetch-latest-release.outputs.VERSION_ALPHA }}
        run: .github/workflows/rust-apply-patch.sh
      - name: Create pull request for Alpha
        uses: peter-evans/create-pull-request@v2
        if: steps.apply-patch-alpha.outputs.UPDATE_NEEDED == 1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ steps.fetch-latest-release.outputs.BASE_BRANCH_ALPHA }}
          branch: rust-${{ steps.fetch-latest-release.outputs.VERSION_ALPHA }}-alpha
          author: Flatcar Buildbot <buildbot@flatcar-linux.org>
          committer: Flatcar Buildbot <buildbot@flatcar-linux.org>
          title: Upgrade Rust in Alpha from ${{ steps.apply-patch-alpha.outputs.VERSION_OLD }} to ${{ steps.fetch-latest-release.outputs.VERSION_ALPHA }}
          commit-message: Upgrade Rust in Alpha from ${{ steps.apply-patch-alpha.outputs.VERSION_OLD }} to ${{ steps.fetch-latest-release.outputs.VERSION_ALPHA }}
          body: Upgrade Rust in Alpha from ${{ steps.apply-patch-alpha.outputs.VERSION_OLD }} to ${{ steps.fetch-latest-release.outputs.VERSION_ALPHA }}
          labels: alpha
      - name: Send repository dispatch to portage-stable
        uses: peter-evans/repository-dispatch@v1.0.0
        if: steps.apply-patch-alpha.outputs.UPDATE_NEEDED == 1
        with:
          token: ${{ secrets.FLATCAR_PORTAGE_STABLE_ACCESS_TOKEN }}
          repository: flatcar-linux/portage-stable
          event-type: cargo-pull-request-alpha
